CREATE TABLE login (
    email TEXT NOT NULL PRIMARY KEY,
    password TEXT NOT  NULL
);

CREATE TABLE todo_chart (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    date TEXT NOT NULL,
    login TEXT NOT NULL,
    FOREIGN KEY (login) REFERENCES login(email)
);
